# Generated by Django 4.2.13 on 2024-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aud', '0002_alter_exchangerate_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Курс валют', 'verbose_name_plural': 'Курс валют'},
        ),
    ]
